telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://f53e-178-176-14-153.ngrok.io"
  bot-name: "@igor7702testbot"
  bot-token: "5276533294:AAFwk5tSnqX3pZ4Ttp-u2oA6WRjHvPQI_F4"
# ChatId: 5297506090
# https://api.telegram.org/bot5276533294:AAFwk5tSnqX3pZ4Ttp-u2oA6WRjHvPQI_F4/setWebhook?url=https://a2d9-178-176-14-153.ngrok.io
# https://api.telegram.org/bot5276533294:AAFwk5tSnqX3pZ4Ttp-u2oA6WRjHvPQI_F4/setWebhook?url=https://be9b-178-176-14-153.ngrok.io
# Пересылка сообщения в чат
# https://api.telegram.org/bot5276533294:AAFwk5tSnqX3pZ4Ttp-u2oA6WRjHvPQI_F4/sendMessage?chat_id=5297506090&text=%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82%20%D0%BC%D0%B8%D1%80
# Получение информации о боте

server:
    port: "5000"