telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://c7ac-178-176-14-153.ngrok.io"
  bot-name: "@igor7702testbot"
  bot-token: "5276533294:AAFwk5tSnqX3pZ4Ttp-u2oA6WRjHvPQI_F4"
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    ssl: true
server:
    port: 4040