telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://0352-178-176-14-153.ngrok.io"
  bot-name: "@igor7702testbot"
  bot-token: "5276533294:AAFwk5tSnqX3pZ4Ttp-u2oA6WRjHvPQI_F4"
server:
    port: "5000"